// ============================================
// DATA.JS - Starter vocabulary & topic data
// ============================================

const STARTER_VOCABULARY = [
    // === HOME LIFE ===
    { korean: "밥", english: "rice / meal", reading: "bap", topic: "home", level: "TOPIK1", notes: "Also means 'meal' generally" },
    { korean: "먹다", english: "to eat", reading: "meokda", topic: "home", level: "TOPIK1", notes: "Informal: 먹어" },
    { korean: "마시다", english: "to drink", reading: "masida", topic: "home", level: "TOPIK1", notes: "Informal: 마셔" },
    { korean: "자다", english: "to sleep", reading: "jada", topic: "home", level: "TOPIK1", notes: "Informal: 자" },
    { korean: "일어나다", english: "to wake up", reading: "ireonada", topic: "home", level: "TOPIK1", notes: "Informal: 일어나" },
    { korean: "씻다", english: "to wash", reading: "ssitda", topic: "home", level: "TOPIK1", notes: "Informal: 씻어" },
    { korean: "청소하다", english: "to clean", reading: "cheongsohada", topic: "home", level: "TOPIK2", notes: "Informal: 청소해" },
    { korean: "요리하다", english: "to cook", reading: "yorihada", topic: "home", level: "TOPIK2", notes: "Informal: 요리해" },
    { korean: "설거지하다", english: "to do dishes", reading: "seolgeojihada", topic: "home", level: "TOPIK2", notes: "Informal: 설거지해" },
    { korean: "빨래하다", english: "to do laundry", reading: "ppallaehada", topic: "home", level: "TOPIK2", notes: "Informal: 빨래해" },
    { korean: "쓰레기", english: "trash", reading: "sseuregi", topic: "home", level: "TOPIK1", notes: "" },
    { korean: "치우다", english: "to tidy up", reading: "chiuda", topic: "home", level: "TOPIK2", notes: "Informal: 치워" },
    { korean: "편안하다", english: "to be comfortable", reading: "pyeonanhada", topic: "home", level: "TOPIK2", notes: "Informal: 편안해" },
    { korean: "춥다", english: "to be cold", reading: "chupda", topic: "home", level: "TOPIK1", notes: "Informal: 추워" },
    { korean: "덥다", english: "to be hot", reading: "deopda", topic: "home", level: "TOPIK1", notes: "Informal: 더워" },
    { korean: "창문", english: "window", reading: "changmun", topic: "home", level: "TOPIK1", notes: "" },
    { korean: "문", english: "door", reading: "mun", topic: "home", level: "TOPIK1", notes: "" },
    { korean: "불", english: "light / fire", reading: "bul", topic: "home", level: "TOPIK1", notes: "Turn off: 불 꺼" },
    { korean: "끄다", english: "to turn off", reading: "kkeuda", topic: "home", level: "TOPIK1", notes: "Informal: 꺼" },
    { korean: "켜다", english: "to turn on", reading: "kyeoda", topic: "home", level: "TOPIK1", notes: "Informal: 켜" },

    // === CAT ===
    { korean: "고양이", english: "cat", reading: "goyangi", topic: "cat", level: "TOPIK1", notes: "" },
    { korean: "귀여워", english: "cute (informal)", reading: "gwiyeowo", topic: "cat", level: "TOPIK1", notes: "Adjective form: 귀엽다" },
    { korean: "밥 주다", english: "to feed", reading: "bap juda", topic: "cat", level: "TOPIK1", notes: "Informal: 밥 줘" },
    { korean: "물", english: "water", reading: "mul", topic: "cat", level: "TOPIK1", notes: "" },
    { korean: "모래", english: "litter / sand", reading: "morae", topic: "cat", level: "TOPIK2", notes: "Cat litter: 고양이 모래" },
    { korean: "간식", english: "snack / treat", reading: "gansik", topic: "cat", level: "TOPIK2", notes: "" },
    { korean: "자다", english: "to sleep", reading: "jada", topic: "cat", level: "TOPIK1", notes: "Cats sleep a lot!" },
    { korean: "놀다", english: "to play", reading: "nolda", topic: "cat", level: "TOPIK1", notes: "Informal: 놀아" },
    { korean: "쓰다듬다", english: "to pet / stroke", reading: "sseudeudeumda", topic: "cat", level: "TOPIK2", notes: "Informal: 쓰다듬어" },
    { korean: "야옹", english: "meow", reading: "yaong", topic: "cat", level: "TOPIK1", notes: "Onomatopoeia" },
    { korean: "털", english: "fur / hair", reading: "teol", topic: "cat", level: "TOPIK2", notes: "" },
    { korean: "발톱", english: "claw / nail", reading: "baltop", topic: "cat", level: "TOPIK3", notes: "" },

    // === GARDEN ===
    { korean: "정원", english: "garden", reading: "jeongwon", topic: "garden", level: "TOPIK2", notes: "" },
    { korean: "꽃", english: "flower", reading: "kkot", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "나무", english: "tree", reading: "namu", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "풀", english: "grass / weed", reading: "pul", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "씨앗", english: "seed", reading: "ssiat", topic: "garden", level: "TOPIK2", notes: "" },
    { korean: "심다", english: "to plant", reading: "simda", topic: "garden", level: "TOPIK2", notes: "Informal: 심어" },
    { korean: "물 주다", english: "to water", reading: "mul juda", topic: "garden", level: "TOPIK1", notes: "Informal: 물 줘" },
    { korean: "자라다", english: "to grow", reading: "jarada", topic: "garden", level: "TOPIK2", notes: "Informal: 자라" },
    { korean: "수확하다", english: "to harvest", reading: "suhwakhada", topic: "garden", level: "TOPIK3", notes: "Informal: 수확해" },
    { korean: "흙", english: "soil / dirt", reading: "heuk", topic: "garden", level: "TOPIK2", notes: "" },
    { korean: "봄", english: "spring", reading: "bom", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "여름", english: "summer", reading: "yeoreum", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "가을", english: "autumn / fall", reading: "gaeul", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "겨울", english: "winter", reading: "gyeoul", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "햇빛", english: "sunlight", reading: "haetbit", topic: "garden", level: "TOPIK2", notes: "" },
    { korean: "비", english: "rain", reading: "bi", topic: "garden", level: "TOPIK1", notes: "" },

    // === CHURCH & FAITH ===
    { korean: "교회", english: "church", reading: "gyohoe", topic: "church", level: "TOPIK1", notes: "" },
    { korean: "예배", english: "worship service", reading: "yebae", topic: "church", level: "TOPIK2", notes: "" },
    { korean: "기도하다", english: "to pray", reading: "gidohada", topic: "church", level: "TOPIK2", notes: "Informal: 기도해" },
    { korean: "찬양하다", english: "to praise / worship", reading: "chanyanghada", topic: "church", level: "TOPIK3", notes: "Informal: 찬양해" },
    { korean: "설교", english: "sermon", reading: "seolgyo", topic: "church", level: "TOPIK3", notes: "" },
    { korean: "성경", english: "Bible", reading: "seonggyeong", topic: "church", level: "TOPIK2", notes: "" },
    { korean: "목사님", english: "pastor (honorific)", reading: "moksanim", topic: "church", level: "TOPIK2", notes: "Always use 님 for pastor" },
    { korean: "집사님", english: "deacon / deaconess", reading: "jipsanim", topic: "church", level: "TOPIK3", notes: "" },
    { korean: "성도", english: "believer / saint", reading: "seongdo", topic: "church", level: "TOPIK3", notes: "" },
    { korean: "은혜", english: "grace", reading: "eunhye", topic: "church", level: "TOPIK3", notes: "Core Reformed concept" },
    { korean: "구원", english: "salvation", reading: "guwon", topic: "church", level: "TOPIK3", notes: "" },
    { korean: "회개하다", english: "to repent", reading: "hoegaehada", topic: "church", level: "TOPIK3", notes: "Informal: 회개해" },
    { korean: "믿음", english: "faith", reading: "mideum", topic: "church", level: "TOPIK2", notes: "" },
    { korean: "사랑", english: "love", reading: "sarang", topic: "church", level: "TOPIK1", notes: "1 Cor 13:13" },
    { korean: "평화", english: "peace", reading: "pyeonghwa", topic: "church", level: "TOPIK2", notes: "" },
    { korean: "주일", english: "Sunday / the Lord's Day", reading: "juil", topic: "church", level: "TOPIK2", notes: "" },
    { korean: "새벽기도", english: "dawn prayer", reading: "saebyeokgido", topic: "church", level: "TOPIK3", notes: "Very Korean church tradition" },
    { korean: "수요예배", english: "Wednesday service", reading: "suyoyebae", topic: "church", level: "TOPIK3", notes: "" },
    { korean: "금요기도회", english: "Friday prayer meeting", reading: "geumyogidohoe", topic: "church", level: "TOPIK3", notes: "" },
    { korean: "청년부", english: "young adult ministry", reading: "cheongnyeonbu", topic: "church", level: "TOPIK3", notes: "" },

    // === MUSIC ===
    { korean: "노래", english: "song", reading: "norae", topic: "music", level: "TOPIK1", notes: "" },
    { korean: "음악", english: "music", reading: "eumak", topic: "music", level: "TOPIK1", notes: "" },
    { korean: "부르다", english: "to sing", reading: "bureuda", topic: "music", level: "TOPIK1", notes: "Informal: 불러" },
    { korean: "연주하다", english: "to play (instrument)", reading: "yeonjuhada", topic: "music", level: "TOPIK2", notes: "Informal: 연주해" },
    { korean: "기타", english: "guitar", reading: "gita", topic: "music", level: "TOPIK1", notes: "" },
    { korean: "피아노", english: "piano", reading: "piano", topic: "music", level: "TOPIK1", notes: "" },
    { korean: "화음", english: "harmony / chord", reading: "hwaeum", topic: "music", level: "TOPIK3", notes: "" },
    { korean: "악보", english: "sheet music", reading: "akbo", topic: "music", level: "TOPIK3", notes: "" },
    { korean: "박자", english: "beat / rhythm", reading: "bakja", topic: "music", level: "TOPIK3", notes: "" },
    { korean: "멜로디", english: "melody", reading: "mellodi", topic: "music", level: "TOPIK2", notes: "" },
    { korean: "가사", english: "lyrics", reading: "gasa", topic: "music", level: "TOPIK2", notes: "" },
    { korean: "찬송가", english: "hymn", reading: "chansongga", topic: "music", level: "TOPIK3", notes: "" },

    // === FAMILY ===
    { korean: "가족", english: "family", reading: "gajok", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "아내", english: "wife", reading: "anae", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "남편", english: "husband", reading: "nampyeon", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "어머니", english: "mother", reading: "eomeoni", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "아버지", english: "father", reading: "abeoji", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "장모님", english: "mother-in-law (wife's mother)", reading: "jangmonim", topic: "family", level: "TOPIK3", notes: "Honorific: 님" },
    { korean: "장인어른", english: "father-in-law (wife's father)", reading: "jangineoreun", topic: "family", level: "TOPIK3", notes: "Very respectful term" },
    { korean: "형", english: "older brother (male speaker)", reading: "hyeong", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "누나", english: "older sister (male speaker)", reading: "nuna", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "오빠", english: "older brother (female speaker)", reading: "oppa", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "언니", english: "older sister (female speaker)", reading: "eonni", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "동생", english: "younger sibling", reading: "dongsaeng", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "조카", english: "nephew / niece", reading: "joka", topic: "family", level: "TOPIK2", notes: "" },
    { korean: "할머니", english: "grandmother", reading: "halmeoni", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "할아버지", english: "grandfather", reading: "harabeoji", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "안부", english: "regards / well-being", reading: "anbu", topic: "family", level: "TOPIK3", notes: "안부 묻다 = ask how someone is" },
    { korean: "인사하다", english: "to greet", reading: "insahada", topic: "family", level: "TOPIK2", notes: "Informal: 인사해" },
    { korean: "선물", english: "gift", reading: "seonmul", topic: "family", level: "TOPIK1", notes: "" },

    // === RENT / HOUSE ===
    { korean: "집", english: "house / home", reading: "jip", topic: "rent", level: "TOPIK1", notes: "" },
    { korean: "월세", english: "monthly rent", reading: "wolse", topic: "rent", level: "TOPIK2", notes: "" },
    { korean: "집주인", english: "landlord", reading: "jibjuin", topic: "rent", level: "TOPIK2", notes: "" },
    { korean: "계약", english: "contract", reading: "gyeyak", topic: "rent", level: "TOPIK3", notes: "" },
    { korean: "보증금", english: "deposit", reading: "bojeunggeum", topic: "rent", level: "TOPIK3", notes: "Key money in Korea" },
    { korean: "수리하다", english: "to repair", reading: "surihada", topic: "rent", level: "TOPIK3", notes: "Informal: 수리해" },
    { korean: "고장", english: "breakdown / malfunction", reading: "gojang", topic: "rent", level: "TOPIK3", notes: "" },
    { korean: "누수", english: "water leak", reading: "nusu", topic: "rent", level: "TOPIK4", notes: "" },
    { korean: "이사하다", english: "to move (house)", reading: "isahada", topic: "rent", level: "TOPIK2", notes: "Informal: 이사해" },
    { korean: "방", english: "room", reading: "bang", topic: "rent", level: "TOPIK1", notes: "" },
    { korean: "부엌", english: "kitchen", reading: "bueok", topic: "rent", level: "TOPIK1", notes: "" },
    { korean: "화장실", english: "bathroom", reading: "hwajangsil", topic: "rent", level: "TOPIK1", notes: "" },

    // === MEDICAL (Starter) ===
    { korean: "병원", english: "hospital", reading: "byeongwon", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "의사", english: "doctor", reading: "uisa", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "환자", english: "patient", reading: "hwanja", topic: "medical", level: "TOPIK2", notes: "" },
    { korean: "아프다", english: "to hurt / be sick", reading: "apeuda", topic: "medical", level: "TOPIK1", notes: "Informal: 아파" },
    { korean: "어디가 아프세요?", english: "Where does it hurt?", reading: "eodiga apuseyo?", topic: "medical", level: "TOPIK2", notes: "Formal patient question" },
    { korean: "머리", english: "head", reading: "meori", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "배", english: "stomach / belly", reading: "bae", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "팔", english: "arm", reading: "pal", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "다리", english: "leg", reading: "dari", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "등", english: "back", reading: "deung", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "약", english: "medicine", reading: "yak", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "처방", english: "prescription", reading: "cheobang", topic: "medical", level: "TOPIK3", notes: "" },
    { korean: "진료", english: "medical examination", reading: "jillyo", topic: "medical", level: "TOPIK3", notes: "" },
    { korean: "검사", english: "test / exam", reading: "geomsa", topic: "medical", level: "TOPIK2", notes: "" },
    { korean: "혈압", english: "blood pressure", reading: "hyeolap", topic: "medical", level: "TOPIK3", notes: "血壓 - Sino-Korean" },
    { korean: "당뇨", english: "diabetes", reading: "dangnyo", topic: "medical", level: "TOPIK3", notes: "" },
    { korean: "감기", english: "cold (illness)", reading: "gamgi", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "열", english: "fever", reading: "yeol", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "기침", english: "cough", reading: "gichim", topic: "medical", level: "TOPIK2", notes: "" },
    { korean: "건강", english: "health", reading: "geongang", topic: "medical", level: "TOPIK2", notes: "" },
    { korean: "가정의학과", english: "family medicine", reading: "gajeonguihakgwa", topic: "medical", level: "TOPIK4", notes: "Your specialty!" },
    { korean: "예방접종", english: "vaccination", reading: "yebangjeopjong", topic: "medical", level: "TOPIK4", notes: "" },
    { korean: "만성질환", english: "chronic disease", reading: "manseongjilhwan", topic: "medical", level: "TOPIK4", notes: "" },
    { korean: "건강검진", english: "health checkup", reading: "geonganggeumjin", topic: "medical", level: "TOPIK3", notes: "" },

    // === ART & CHEMISTRY (Wife's interests) ===
    { korean: "그림", english: "picture / painting", reading: "geurim", topic: "art", level: "TOPIK1", notes: "" },
    { korean: "예술", english: "art", reading: "yesul", topic: "art", level: "TOPIK2", notes: "" },
    { korean: "물감", english: "paint / pigment", reading: "mulgam", topic: "art", level: "TOPIK3", notes: "" },
    { korean: "붓", english: "brush", reading: "but", topic: "art", level: "TOPIK2", notes: "" },
    { korean: "캔버스", english: "canvas", reading: "kaenbeoseu", topic: "art", level: "TOPIK2", notes: "" },
    { korean: "화학", english: "chemistry", reading: "hwahak", topic: "chemistry", level: "TOPIK3", notes: "" },
    { korean: "생물", english: "biology", reading: "saengmul", topic: "chemistry", level: "TOPIK3", notes: "" },
    { korean: "실험", english: "experiment", reading: "sirheom", topic: "chemistry", level: "TOPIK3", notes: "" },
    { korean: "원소", english: "element", reading: "wonso", topic: "chemistry", level: "TOPIK4", notes: "" },
    { korean: "분자", english: "molecule", reading: "bunja", topic: "chemistry", level: "TOPIK4", notes: "" },
    { korean: "반응", english: "reaction", reading: "baneung", topic: "chemistry", level: "TOPIK3", notes: "" },
    { korean: "영어", english: "English", reading: "yeongeo", topic: "chemistry", level: "TOPIK1", notes: "" },

    // === EVERYDAY PHRASES ===
    { korean: "안녕하세요", english: "Hello (formal)", reading: "annyeonghaseyo", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "감사합니다", english: "Thank you", reading: "gamsahamnida", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "죄송합니다", english: "I'm sorry", reading: "joesonghamnida", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "괜찮아요", english: "It's okay / I'm fine", reading: "gwaenchanayo", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "잘했어", english: "You did well / Good job", reading: "jalhaesseo", topic: "phrases", level: "TOPIK1", notes: "Informal encouragement" },
    { korean: "화이팅", english: "Fighting! / You can do it!", reading: "hwaiting", topic: "phrases", level: "TOPIK1", notes: "Konglish but essential" },
    { korean: "사랑해", english: "I love you (informal)", reading: "saranghae", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "보고 싶어", english: "I miss you", reading: "bogo sipeo", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "오늘", english: "today", reading: "oneul", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "내일", english: "tomorrow", reading: "naeil", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "어제", english: "yesterday", reading: "eoje", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "지금", english: "now", reading: "jigeum", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "나중에", english: "later", reading: "najunge", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "어디", english: "where", reading: "eodi", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "언제", english: "when", reading: "eonje", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "뭐", english: "what", reading: "mwo", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "왜", english: "why", reading: "wae", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "어떻게", english: "how", reading: "eotteoke", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "많이", english: "a lot / very", reading: "mani", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "조금", english: "a little", reading: "jogeum", topic: "phrases", level: "TOPIK1", notes: "" },

    // === DAILY LIFE — Core Verbs & Time ===
    { korean: "가다", english: "to go", reading: "gada", topic: "daily", level: "TOPIK1", notes: "Informal: 가" },
    { korean: "오다", english: "to come", reading: "oda", topic: "daily", level: "TOPIK1", notes: "Informal: 와" },
    { korean: "있다", english: "to exist / to have", reading: "itda", topic: "daily", level: "TOPIK1", notes: "있어 (informal)" },
    { korean: "없다", english: "to not have / to be absent", reading: "eopda", topic: "daily", level: "TOPIK1", notes: "없어 (informal)" },
    { korean: "하다", english: "to do", reading: "hada", topic: "daily", level: "TOPIK1", notes: "Informal: 해" },
    { korean: "되다", english: "to become", reading: "doeda", topic: "daily", level: "TOPIK1", notes: "Informal: 돼" },
    { korean: "알다", english: "to know", reading: "alda", topic: "daily", level: "TOPIK1", notes: "Informal: 알아" },
    { korean: "모르다", english: "to not know", reading: "moreuda", topic: "daily", level: "TOPIK1", notes: "Informal: 몰라" },
    { korean: "보다", english: "to see / watch", reading: "boda", topic: "daily", level: "TOPIK1", notes: "Informal: 봐" },
    { korean: "듣다", english: "to hear / listen", reading: "deutda", topic: "daily", level: "TOPIK1", notes: "Informal: 들어" },
    { korean: "말하다", english: "to speak / say", reading: "malhada", topic: "daily", level: "TOPIK1", notes: "Informal: 말해" },
    { korean: "읽다", english: "to read", reading: "ikda", topic: "daily", level: "TOPIK1", notes: "Informal: 읽어" },
    { korean: "쓰다", english: "to write / use", reading: "sseuda", topic: "daily", level: "TOPIK1", notes: "Informal: 써" },
    { korean: "주다", english: "to give", reading: "juda", topic: "daily", level: "TOPIK1", notes: "Informal: 줘" },
    { korean: "받다", english: "to receive", reading: "batda", topic: "daily", level: "TOPIK1", notes: "Informal: 받아" },
    { korean: "좋아하다", english: "to like", reading: "joahada", topic: "daily", level: "TOPIK1", notes: "Informal: 좋아해" },
    { korean: "공부하다", english: "to study", reading: "gongbuhada", topic: "daily", level: "TOPIK1", notes: "Informal: 공부해" },
    { korean: "아침", english: "morning", reading: "achim", topic: "daily", level: "TOPIK1", notes: "" },
    { korean: "저녁", english: "evening", reading: "jeonyeok", topic: "daily", level: "TOPIK1", notes: "" },
    { korean: "밤", english: "night", reading: "bam", topic: "daily", level: "TOPIK1", notes: "" },
    { korean: "시간", english: "time / hour", reading: "sigan", topic: "daily", level: "TOPIK1", notes: "" },
    { korean: "매일", english: "every day", reading: "maeil", topic: "daily", level: "TOPIK1", notes: "" },
    { korean: "주말", english: "weekend", reading: "jumal", topic: "daily", level: "TOPIK2", notes: "" },
    { korean: "항상", english: "always", reading: "hangsang", topic: "daily", level: "TOPIK2", notes: "" },
    { korean: "가끔", english: "sometimes", reading: "gakkeum", topic: "daily", level: "TOPIK2", notes: "" },

    // === FOOD & DINING ===
    { korean: "국", english: "soup", reading: "guk", topic: "food", level: "TOPIK1", notes: "" },
    { korean: "고기", english: "meat", reading: "gogi", topic: "food", level: "TOPIK1", notes: "" },
    { korean: "생선", english: "fish", reading: "saengseon", topic: "food", level: "TOPIK1", notes: "" },
    { korean: "채소", english: "vegetable", reading: "chaeso", topic: "food", level: "TOPIK1", notes: "" },
    { korean: "과일", english: "fruit", reading: "gwail", topic: "food", level: "TOPIK1", notes: "" },
    { korean: "빵", english: "bread", reading: "ppang", topic: "food", level: "TOPIK1", notes: "" },
    { korean: "우유", english: "milk", reading: "uyu", topic: "food", level: "TOPIK1", notes: "" },
    { korean: "커피", english: "coffee", reading: "keopi", topic: "food", level: "TOPIK1", notes: "" },
    { korean: "차", english: "tea", reading: "cha", topic: "food", level: "TOPIK1", notes: "" },
    { korean: "김치", english: "kimchi", reading: "gimchi", topic: "food", level: "TOPIK1", notes: "" },
    { korean: "달걀", english: "egg", reading: "dalgyal", topic: "food", level: "TOPIK1", notes: "" },
    { korean: "맛있다", english: "to be delicious", reading: "masitda", topic: "food", level: "TOPIK1", notes: "Informal: 맛있어" },
    { korean: "맛없다", english: "to be tasteless", reading: "maseopda", topic: "food", level: "TOPIK1", notes: "Informal: 맛없어" },
    { korean: "배고프다", english: "to be hungry", reading: "baegopuda", topic: "food", level: "TOPIK1", notes: "Informal: 배고파" },
    { korean: "배부르다", english: "to be full", reading: "baebureuda", topic: "food", level: "TOPIK2", notes: "Informal: 배불러" },
    { korean: "식당", english: "restaurant", reading: "sikdang", topic: "food", level: "TOPIK1", notes: "" },
    { korean: "주문하다", english: "to order (food)", reading: "jumunhada", topic: "food", level: "TOPIK2", notes: "Informal: 주문해" },
    { korean: "반찬", english: "side dish", reading: "banchan", topic: "food", level: "TOPIK2", notes: "The small dishes alongside rice" },

    // === TRANSPORTATION ===
    { korean: "버스", english: "bus", reading: "beoseu", topic: "transport", level: "TOPIK1", notes: "" },
    { korean: "지하철", english: "subway / metro", reading: "jihacheol", topic: "transport", level: "TOPIK1", notes: "" },
    { korean: "택시", english: "taxi", reading: "taeksi", topic: "transport", level: "TOPIK1", notes: "" },
    { korean: "기차", english: "train", reading: "gicha", topic: "transport", level: "TOPIK1", notes: "" },
    { korean: "비행기", english: "airplane", reading: "bihaenggi", topic: "transport", level: "TOPIK1", notes: "" },
    { korean: "자동차", english: "car", reading: "jadongcha", topic: "transport", level: "TOPIK1", notes: "" },
    { korean: "역", english: "station", reading: "yeok", topic: "transport", level: "TOPIK1", notes: "" },
    { korean: "공항", english: "airport", reading: "gonghang", topic: "transport", level: "TOPIK1", notes: "" },
    { korean: "타다", english: "to ride / take (transport)", reading: "tada", topic: "transport", level: "TOPIK1", notes: "Informal: 타" },
    { korean: "내리다", english: "to get off (transport)", reading: "naerida", topic: "transport", level: "TOPIK1", notes: "Informal: 내려" },
    { korean: "길", english: "road / street / way", reading: "gil", topic: "transport", level: "TOPIK1", notes: "" },
    { korean: "지도", english: "map", reading: "jido", topic: "transport", level: "TOPIK1", notes: "" },
    { korean: "왼쪽", english: "left side", reading: "oenjjok", topic: "transport", level: "TOPIK1", notes: "" },
    { korean: "오른쪽", english: "right side", reading: "oreunjjok", topic: "transport", level: "TOPIK1", notes: "" },

    // === EMOTIONS & FEELINGS ===
    { korean: "화나다", english: "to be angry", reading: "hwanada", topic: "emotions", level: "TOPIK1", notes: "Informal: 화나" },
    { korean: "피곤하다", english: "to be tired", reading: "pigonhada", topic: "emotions", level: "TOPIK1", notes: "Informal: 피곤해" },
    { korean: "기쁘다", english: "to be joyful", reading: "gippeuda", topic: "emotions", level: "TOPIK2", notes: "Informal: 기뻐" },
    { korean: "슬프다", english: "to be sad", reading: "seulpeuda", topic: "emotions", level: "TOPIK2", notes: "Informal: 슬퍼" },
    { korean: "무섭다", english: "to be scared", reading: "museopda", topic: "emotions", level: "TOPIK2", notes: "Informal: 무서워" },
    { korean: "외롭다", english: "to be lonely", reading: "oeropda", topic: "emotions", level: "TOPIK2", notes: "Informal: 외로워" },
    { korean: "즐겁다", english: "to be enjoyable / fun", reading: "jeulgeopda", topic: "emotions", level: "TOPIK2", notes: "Informal: 즐거워" },
    { korean: "행복하다", english: "to be happy", reading: "haengbokhada", topic: "emotions", level: "TOPIK2", notes: "Informal: 행복해" },
    { korean: "걱정하다", english: "to worry", reading: "geokjeonghada", topic: "emotions", level: "TOPIK2", notes: "Informal: 걱정해" },
    { korean: "긴장하다", english: "to be nervous", reading: "ginjanghada", topic: "emotions", level: "TOPIK2", notes: "Informal: 긴장해" },
    { korean: "그립다", english: "to miss (someone / home)", reading: "geurip-da", topic: "emotions", level: "TOPIK3", notes: "Informal: 그리워" },
    { korean: "설레다", english: "to feel excited / have butterflies", reading: "seolleda", topic: "emotions", level: "TOPIK3", notes: "Informal: 설레" },
    { korean: "실망하다", english: "to be disappointed", reading: "silmanghada", topic: "emotions", level: "TOPIK3", notes: "Informal: 실망해" },
    { korean: "부끄럽다", english: "to be embarrassed", reading: "bukkeureop-da", topic: "emotions", level: "TOPIK3", notes: "Informal: 부끄러워" },

    // === FAMILY (additional) ===
    { korean: "딸", english: "daughter", reading: "ttal", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "아들", english: "son", reading: "adeul", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "부모님", english: "parents (honorific)", reading: "bumonim", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "사촌", english: "cousin", reading: "sachon", topic: "family", level: "TOPIK2", notes: "" },
    { korean: "사위", english: "son-in-law", reading: "sawi", topic: "family", level: "TOPIK3", notes: "" },
    { korean: "며느리", english: "daughter-in-law", reading: "myeonneuri", topic: "family", level: "TOPIK3", notes: "" },

    // === BODY & MEDICAL (extended) ===
    { korean: "눈", english: "eye(s)", reading: "nun", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "코", english: "nose", reading: "ko", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "입", english: "mouth", reading: "ip", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "귀", english: "ear(s)", reading: "gwi", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "손", english: "hand(s)", reading: "son", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "발", english: "foot / feet", reading: "bal", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "목", english: "throat / neck", reading: "mok", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "허리", english: "lower back / waist", reading: "heori", topic: "medical", level: "TOPIK2", notes: "" },
    { korean: "가슴", english: "chest", reading: "gaseum", topic: "medical", level: "TOPIK2", notes: "" },
    { korean: "심장", english: "heart", reading: "simjang", topic: "medical", level: "TOPIK3", notes: "心臟 — Sino-Korean" },
    { korean: "폐", english: "lung", reading: "pye", topic: "medical", level: "TOPIK3", notes: "肺" },
    { korean: "간", english: "liver", reading: "gan", topic: "medical", level: "TOPIK3", notes: "肝" },
    { korean: "간호사", english: "nurse", reading: "ganhosa", topic: "medical", level: "TOPIK2", notes: "" },
    { korean: "수술", english: "surgery", reading: "susul", topic: "medical", level: "TOPIK3", notes: "" },
    { korean: "입원", english: "hospitalization", reading: "ibwon", topic: "medical", level: "TOPIK3", notes: "" },
    { korean: "퇴원", english: "hospital discharge", reading: "toewon", topic: "medical", level: "TOPIK3", notes: "" },
    { korean: "증상", english: "symptom", reading: "jeungsang", topic: "medical", level: "TOPIK3", notes: "症狀" },
    { korean: "진단", english: "diagnosis", reading: "jindan", topic: "medical", level: "TOPIK3", notes: "診斷" },
    { korean: "두통", english: "headache", reading: "dutong", topic: "medical", level: "TOPIK2", notes: "頭痛" },
    { korean: "복통", english: "stomachache", reading: "boktong", topic: "medical", level: "TOPIK3", notes: "腹痛" },
    { korean: "통증", english: "pain", reading: "tongjjeung", topic: "medical", level: "TOPIK3", notes: "痛症" },
    { korean: "혈액", english: "blood", reading: "hyeoraek", topic: "medical", level: "TOPIK3", notes: "血液" },
    { korean: "응급실", english: "emergency room", reading: "eunggeupsil", topic: "medical", level: "TOPIK3", notes: "" },
    { korean: "치료", english: "treatment", reading: "chiryo", topic: "medical", level: "TOPIK3", notes: "治療" },
    { korean: "주사", english: "injection / shot", reading: "jusa", topic: "medical", level: "TOPIK2", notes: "" },
    { korean: "독감", english: "influenza / flu", reading: "dokgam", topic: "medical", level: "TOPIK3", notes: "" },
    { korean: "암", english: "cancer", reading: "am", topic: "medical", level: "TOPIK3", notes: "癌" },
    { korean: "골절", english: "fracture", reading: "gojeol", topic: "medical", level: "TOPIK4", notes: "骨折" },
    { korean: "염증", english: "inflammation", reading: "yeomjeung", topic: "medical", level: "TOPIK4", notes: "炎症 — key Sino-Korean root" },
];

// Topic metadata for UI
const TOPIC_METADATA = {
    home: { icon: "🏠", label: "Home Life", color: "#E74C3C" },
    cat: { icon: "🐱", label: "Cat", color: "#F39C12" },
    garden: { icon: "🌱", label: "Garden", color: "#27AE60" },
    church: { icon: "⛪", label: "Church & Faith", color: "#9B59B6" },
    music: { icon: "🎵", label: "Music", color: "#E91E63" },
    family: { icon: "👨‍👩‍👧‍👦", label: "Family", color: "#FF5722" },
    rent: { icon: "🏠", label: "Rent & House", color: "#795548" },
    medical: { icon: "🏥", label: "Medical", color: "#2196F3" },
    art: { icon: "🎨", label: "Art", color: "#FF9800" },
    chemistry: { icon: "⚗️", label: "Chemistry & Biology", color: "#00BCD4" },
    phrases: { icon: "💬", label: "Everyday Phrases", color: "#607D8B" },
    daily: { icon: "📅", label: "Daily Life", color: "#FF5722" },
    food: { icon: "🍱", label: "Food & Dining", color: "#FF9800" },
    transport: { icon: "🚇", label: "Transportation", color: "#546E7A" },
    emotions: { icon: "💭", label: "Emotions & Feelings", color: "#E91E63" },
};

// TOPIK level thresholds
const TOPIK_LEVELS = {
    TOPIK1: { name: "TOPIK I Level 1", minCards: 0, description: "Beginner - basic survival Korean" },
    TOPIK2: { name: "TOPIK I Level 2", minCards: 50, description: "Elementary - simple conversations" },
    TOPIK3: { name: "TOPIK II Level 3", minCards: 150, description: "Intermediate - daily life fluency" },
    TOPIK4: { name: "TOPIK II Level 4", minCards: 300, description: "Upper-Intermediate - social fluency" },
    TOPIK5: { name: "TOPIK II Level 5", minCards: 500, description: "Advanced - professional contexts" },
    TOPIK6: { name: "TOPIK II Level 6", minCards: 800, description: "Proficient - near-native fluency" },
};

// Reading practice sentences (progressive difficulty)
const READING_SENTENCES = [
    { korean: "안녕하세요. 저는 의사예요.", english: "Hello. I am a doctor.", level: 1 },
    { korean: "고양이가 귀여워요.", english: "The cat is cute.", level: 1 },
    { korean: "오늘 날씨가 좋아요.", english: "The weather is good today.", level: 1 },
    { korean: "밥 먹었어요?", english: "Did you eat?", level: 1 },
    { korean: "교회에 가요.", english: "I go to church.", level: 1 },
    { korean: "우리 집에 고양이가 한 마리 있어요.", english: "We have one cat at our house.", level: 2 },
    { korean: "매일 밤 한국어를 공부해요.", english: "I study Korean every night.", level: 2 },
    { korean: "아내는 예술을 좋아해요.", english: "My wife likes art.", level: 2 },
    { korean: "정원에서 꽃을 심었어요.", english: "I planted flowers in the garden.", level: 2 },
    { korean: "주일마다 교회에 가서 예배를 드려요.", english: "Every Sunday I go to church and worship.", level: 2 },
    { korean: "5년 후에 한국에서 의사 시험을 볼 거예요.", english: "In 5 years, I will take the doctor exam in Korea.", level: 3 },
    { korean: "가정의학과 의사로서 환자들을 돌보고 싶어요.", english: "As a family medicine doctor, I want to care for patients.", level: 3 },
    { korean: "아내와 함께 노래하고 음악을 연주하는 것을 좋아해요.", english: "I like singing and playing music with my wife.", level: 3 },
    { korean: "은혜로운 하나님의 사랑을 매일 느껴요.", english: "I feel God's gracious love every day.", level: 3 },
    { korean: "한국에 가면 장인어른과 장모님을 뵙고 싶어요.", english: "When I go to Korea, I want to meet my parents-in-law.", level: 3 },
];
