// ============================================
// DATA.JS - Starter vocabulary & topic data
// ============================================

const STARTER_VOCABULARY = [
    // === HOME LIFE ===
    { korean: "밥", english: "rice / meal", reading: "bap", topic: "home", level: "TOPIK1", notes: "Also means 'meal' generally" },
    { korean: "먹다", english: "to eat", reading: "meokda", topic: "home", level: "TOPIK1", notes: "Informal: 먹어" },
    { korean: "마시다", english: "to drink", reading: "masida", topic: "home", level: "TOPIK1", notes: "Informal: 마셔" },
    { korean: "자다", english: "to sleep", reading: "jada", topic: "home", level: "TOPIK1", notes: "Informal: 자" },
    { korean: "일어나다", english: "to wake up", reading: "ireonada", topic: "home", level: "TOPIK1", notes: "Informal: 일어나" },
    { korean: "씻다", english: "to wash", reading: "ssitda", topic: "home", level: "TOPIK1", notes: "Informal: 씻어" },
    { korean: "청소하다", english: "to clean", reading: "cheongsohada", topic: "home", level: "TOPIK2", notes: "Informal: 청소해" },
    { korean: "요리하다", english: "to cook", reading: "yorihada", topic: "home", level: "TOPIK2", notes: "Informal: 요리해" },
    { korean: "설거지하다", english: "to do dishes", reading: "seolgeojihada", topic: "home", level: "TOPIK2", notes: "Informal: 설거지해" },
    { korean: "빨래하다", english: "to do laundry", reading: "ppallaehada", topic: "home", level: "TOPIK2", notes: "Informal: 빨래해" },
    { korean: "쓰레기", english: "trash", reading: "sseuregi", topic: "home", level: "TOPIK1", notes: "" },
    { korean: "치우다", english: "to tidy up", reading: "chiuda", topic: "home", level: "TOPIK2", notes: "Informal: 치워" },
    { korean: "편안하다", english: "to be comfortable", reading: "pyeonanhada", topic: "home", level: "TOPIK2", notes: "Informal: 편안해" },
    { korean: "춥다", english: "to be cold", reading: "chupda", topic: "home", level: "TOPIK1", notes: "Informal: 추워" },
    { korean: "덥다", english: "to be hot", reading: "deopda", topic: "home", level: "TOPIK1", notes: "Informal: 더워" },
    { korean: "창문", english: "window", reading: "changmun", topic: "home", level: "TOPIK1", notes: "" },
    { korean: "문", english: "door", reading: "mun", topic: "home", level: "TOPIK1", notes: "" },
    { korean: "불", english: "light / fire", reading: "bul", topic: "home", level: "TOPIK1", notes: "Turn off: 불 꺼" },
    { korean: "끄다", english: "to turn off", reading: "kkeuda", topic: "home", level: "TOPIK1", notes: "Informal: 꺼" },
    { korean: "켜다", english: "to turn on", reading: "kyeoda", topic: "home", level: "TOPIK1", notes: "Informal: 켜" },

    // === CAT ===
    { korean: "고양이", english: "cat", reading: "goyangi", topic: "cat", level: "TOPIK1", notes: "" },
    { korean: "귀여워", english: "cute (informal)", reading: "gwiyeowo", topic: "cat", level: "TOPIK1", notes: "Adjective form: 귀엽다" },
    { korean: "밥 주다", english: "to feed", reading: "bap juda", topic: "cat", level: "TOPIK1", notes: "Informal: 밥 줘" },
    { korean: "물", english: "water", reading: "mul", topic: "cat", level: "TOPIK1", notes: "" },
    { korean: "모래", english: "litter / sand", reading: "morae", topic: "cat", level: "TOPIK2", notes: "Cat litter: 고양이 모래" },
    { korean: "간식", english: "snack / treat", reading: "gansik", topic: "cat", level: "TOPIK2", notes: "" },
    { korean: "자다", english: "to sleep", reading: "jada", topic: "cat", level: "TOPIK1", notes: "Cats sleep a lot!" },
    { korean: "놀다", english: "to play", reading: "nolda", topic: "cat", level: "TOPIK1", notes: "Informal: 놀아" },
    { korean: "쓰다듬다", english: "to pet / stroke", reading: "sseudeudeumda", topic: "cat", level: "TOPIK2", notes: "Informal: 쓰다듬어" },
    { korean: "야옹", english: "meow", reading: "yaong", topic: "cat", level: "TOPIK1", notes: "Onomatopoeia" },
    { korean: "털", english: "fur / hair", reading: "teol", topic: "cat", level: "TOPIK2", notes: "" },
    { korean: "발톱", english: "claw / nail", reading: "baltop", topic: "cat", level: "TOPIK3", notes: "" },

    // === GARDEN ===
    { korean: "정원", english: "garden", reading: "jeongwon", topic: "garden", level: "TOPIK2", notes: "" },
    { korean: "꽃", english: "flower", reading: "kkot", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "나무", english: "tree", reading: "namu", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "풀", english: "grass / weed", reading: "pul", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "씨앗", english: "seed", reading: "ssiat", topic: "garden", level: "TOPIK2", notes: "" },
    { korean: "심다", english: "to plant", reading: "simda", topic: "garden", level: "TOPIK2", notes: "Informal: 심어" },
    { korean: "물 주다", english: "to water", reading: "mul juda", topic: "garden", level: "TOPIK1", notes: "Informal: 물 줘" },
    { korean: "자라다", english: "to grow", reading: "jarada", topic: "garden", level: "TOPIK2", notes: "Informal: 자라" },
    { korean: "수확하다", english: "to harvest", reading: "suhwakhada", topic: "garden", level: "TOPIK3", notes: "Informal: 수확해" },
    { korean: "흙", english: "soil / dirt", reading: "heuk", topic: "garden", level: "TOPIK2", notes: "" },
    { korean: "봄", english: "spring", reading: "bom", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "여름", english: "summer", reading: "yeoreum", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "가을", english: "autumn / fall", reading: "gaeul", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "겨울", english: "winter", reading: "gyeoul", topic: "garden", level: "TOPIK1", notes: "" },
    { korean: "햇빛", english: "sunlight", reading: "haetbit", topic: "garden", level: "TOPIK2", notes: "" },
    { korean: "비", english: "rain", reading: "bi", topic: "garden", level: "TOPIK1", notes: "" },

    // === CHURCH & FAITH ===
    { korean: "교회", english: "church", reading: "gyohoe", topic: "church", level: "TOPIK1", notes: "" },
    { korean: "예배", english: "worship service", reading: "yebae", topic: "church", level: "TOPIK2", notes: "" },
    { korean: "기도하다", english: "to pray", reading: "gidohada", topic: "church", level: "TOPIK2", notes: "Informal: 기도해" },
    { korean: "찬양하다", english: "to praise / worship", reading: "chanyanghada", topic: "church", level: "TOPIK3", notes: "Informal: 찬양해" },
    { korean: "설교", english: "sermon", reading: "seolgyo", topic: "church", level: "TOPIK3", notes: "" },
    { korean: "성경", english: "Bible", reading: "seonggyeong", topic: "church", level: "TOPIK2", notes: "" },
    { korean: "목사님", english: "pastor (honorific)", reading: "moksanim", topic: "church", level: "TOPIK2", notes: "Always use 님 for pastor" },
    { korean: "집사님", english: "deacon / deaconess", reading: "jipsanim", topic: "church", level: "TOPIK3", notes: "" },
    { korean: "성도", english: "believer / saint", reading: "seongdo", topic: "church", level: "TOPIK3", notes: "" },
    { korean: "은혜", english: "grace", reading: "eunhye", topic: "church", level: "TOPIK3", notes: "Core Reformed concept" },
    { korean: "구원", english: "salvation", reading: "guwon", topic: "church", level: "TOPIK3", notes: "" },
    { korean: "회개하다", english: "to repent", reading: "hoegaehada", topic: "church", level: "TOPIK3", notes: "Informal: 회개해" },
    { korean: "믿음", english: "faith", reading: "mideum", topic: "church", level: "TOPIK2", notes: "" },
    { korean: "사랑", english: "love", reading: "sarang", topic: "church", level: "TOPIK1", notes: "1 Cor 13:13" },
    { korean: "평화", english: "peace", reading: "pyeonghwa", topic: "church", level: "TOPIK2", notes: "" },
    { korean: "주일", english: "Sunday / the Lord's Day", reading: "juil", topic: "church", level: "TOPIK2", notes: "" },
    { korean: "새벽기도", english: "dawn prayer", reading: "saebyeokgido", topic: "church", level: "TOPIK3", notes: "Very Korean church tradition" },
    { korean: "수요예배", english: "Wednesday service", reading: "suyoyebae", topic: "church", level: "TOPIK3", notes: "" },
    { korean: "금요기도회", english: "Friday prayer meeting", reading: "geumyogidohoe", topic: "church", level: "TOPIK3", notes: "" },
    { korean: "청년부", english: "young adult ministry", reading: "cheongnyeonbu", topic: "church", level: "TOPIK3", notes: "" },

    // === MUSIC ===
    { korean: "노래", english: "song", reading: "norae", topic: "music", level: "TOPIK1", notes: "" },
    { korean: "음악", english: "music", reading: "eumak", topic: "music", level: "TOPIK1", notes: "" },
    { korean: "부르다", english: "to sing", reading: "bureuda", topic: "music", level: "TOPIK1", notes: "Informal: 불러" },
    { korean: "연주하다", english: "to play (instrument)", reading: "yeonjuhada", topic: "music", level: "TOPIK2", notes: "Informal: 연주해" },
    { korean: "기타", english: "guitar", reading: "gita", topic: "music", level: "TOPIK1", notes: "" },
    { korean: "피아노", english: "piano", reading: "piano", topic: "music", level: "TOPIK1", notes: "" },
    { korean: "화음", english: "harmony / chord", reading: "hwaeum", topic: "music", level: "TOPIK3", notes: "" },
    { korean: "악보", english: "sheet music", reading: "akbo", topic: "music", level: "TOPIK3", notes: "" },
    { korean: "박자", english: "beat / rhythm", reading: "bakja", topic: "music", level: "TOPIK3", notes: "" },
    { korean: "멜로디", english: "melody", reading: "mellodi", topic: "music", level: "TOPIK2", notes: "" },
    { korean: "가사", english: "lyrics", reading: "gasa", topic: "music", level: "TOPIK2", notes: "" },
    { korean: "찬송가", english: "hymn", reading: "chansongga", topic: "music", level: "TOPIK3", notes: "" },

    // === FAMILY ===
    { korean: "가족", english: "family", reading: "gajok", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "아내", english: "wife", reading: "anae", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "남편", english: "husband", reading: "nampyeon", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "어머니", english: "mother", reading: "eomeoni", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "아버지", english: "father", reading: "abeoji", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "장모님", english: "mother-in-law (wife's mother)", reading: "jangmonim", topic: "family", level: "TOPIK3", notes: "Honorific: 님" },
    { korean: "장인어른", english: "father-in-law (wife's father)", reading: "jangineoreun", topic: "family", level: "TOPIK3", notes: "Very respectful term" },
    { korean: "형", english: "older brother (male speaker)", reading: "hyeong", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "누나", english: "older sister (male speaker)", reading: "nuna", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "오빠", english: "older brother (female speaker)", reading: "oppa", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "언니", english: "older sister (female speaker)", reading: "eonni", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "동생", english: "younger sibling", reading: "dongsaeng", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "조카", english: "nephew / niece", reading: "joka", topic: "family", level: "TOPIK2", notes: "" },
    { korean: "할머니", english: "grandmother", reading: "halmeoni", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "할아버지", english: "grandfather", reading: "harabeoji", topic: "family", level: "TOPIK1", notes: "" },
    { korean: "안부", english: "regards / well-being", reading: "anbu", topic: "family", level: "TOPIK3", notes: "안부 묻다 = ask how someone is" },
    { korean: "인사하다", english: "to greet", reading: "insahada", topic: "family", level: "TOPIK2", notes: "Informal: 인사해" },
    { korean: "선물", english: "gift", reading: "seonmul", topic: "family", level: "TOPIK1", notes: "" },

    // === RENT / HOUSE ===
    { korean: "집", english: "house / home", reading: "jip", topic: "rent", level: "TOPIK1", notes: "" },
    { korean: "월세", english: "monthly rent", reading: "wolse", topic: "rent", level: "TOPIK2", notes: "" },
    { korean: "집주인", english: "landlord", reading: "jibjuin", topic: "rent", level: "TOPIK2", notes: "" },
    { korean: "계약", english: "contract", reading: "gyeyak", topic: "rent", level: "TOPIK3", notes: "" },
    { korean: "보증금", english: "deposit", reading: "bojeunggeum", topic: "rent", level: "TOPIK3", notes: "Key money in Korea" },
    { korean: "수리하다", english: "to repair", reading: "surihada", topic: "rent", level: "TOPIK3", notes: "Informal: 수리해" },
    { korean: "고장", english: "breakdown / malfunction", reading: "gojang", topic: "rent", level: "TOPIK3", notes: "" },
    { korean: "누수", english: "water leak", reading: "nusu", topic: "rent", level: "TOPIK4", notes: "" },
    { korean: "이사하다", english: "to move (house)", reading: "isahada", topic: "rent", level: "TOPIK2", notes: "Informal: 이사해" },
    { korean: "방", english: "room", reading: "bang", topic: "rent", level: "TOPIK1", notes: "" },
    { korean: "부엌", english: "kitchen", reading: "bueok", topic: "rent", level: "TOPIK1", notes: "" },
    { korean: "화장실", english: "bathroom", reading: "hwajangsil", topic: "rent", level: "TOPIK1", notes: "" },

    // === MEDICAL (Starter) ===
    { korean: "병원", english: "hospital", reading: "byeongwon", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "의사", english: "doctor", reading: "uisa", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "환자", english: "patient", reading: "hwanja", topic: "medical", level: "TOPIK2", notes: "" },
    { korean: "아프다", english: "to hurt / be sick", reading: "apeuda", topic: "medical", level: "TOPIK1", notes: "Informal: 아파" },
    { korean: "어디가 아프세요?", english: "Where does it hurt?", reading: "eodiga apuseyo?", topic: "medical", level: "TOPIK2", notes: "Formal patient question" },
    { korean: "머리", english: "head", reading: "meori", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "배", english: "stomach / belly", reading: "bae", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "팔", english: "arm", reading: "pal", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "다리", english: "leg", reading: "dari", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "등", english: "back", reading: "deung", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "약", english: "medicine", reading: "yak", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "처방", english: "prescription", reading: "cheobang", topic: "medical", level: "TOPIK3", notes: "" },
    { korean: "진료", english: "medical examination", reading: "jillyo", topic: "medical", level: "TOPIK3", notes: "" },
    { korean: "검사", english: "test / exam", reading: "geomsa", topic: "medical", level: "TOPIK2", notes: "" },
    { korean: "혈압", english: "blood pressure", reading: "hyeolap", topic: "medical", level: "TOPIK3", notes: "血壓 - Sino-Korean" },
    { korean: "당뇨", english: "diabetes", reading: "dangnyo", topic: "medical", level: "TOPIK3", notes: "" },
    { korean: "감기", english: "cold (illness)", reading: "gamgi", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "열", english: "fever", reading: "yeol", topic: "medical", level: "TOPIK1", notes: "" },
    { korean: "기침", english: "cough", reading: "gichim", topic: "medical", level: "TOPIK2", notes: "" },
    { korean: "건강", english: "health", reading: "geongang", topic: "medical", level: "TOPIK2", notes: "" },
    { korean: "가정의학과", english: "family medicine", reading: "gajeonguihakgwa", topic: "medical", level: "TOPIK4", notes: "Your specialty!" },
    { korean: "예방접종", english: "vaccination", reading: "yebangjeopjong", topic: "medical", level: "TOPIK4", notes: "" },
    { korean: "만성질환", english: "chronic disease", reading: "manseongjilhwan", topic: "medical", level: "TOPIK4", notes: "" },
    { korean: "건강검진", english: "health checkup", reading: "geonganggeumjin", topic: "medical", level: "TOPIK3", notes: "" },

    // === ART & CHEMISTRY (Wife's interests) ===
    { korean: "그림", english: "picture / painting", reading: "geurim", topic: "art", level: "TOPIK1", notes: "" },
    { korean: "예술", english: "art", reading: "yesul", topic: "art", level: "TOPIK2", notes: "" },
    { korean: "물감", english: "paint / pigment", reading: "mulgam", topic: "art", level: "TOPIK3", notes: "" },
    { korean: "붓", english: "brush", reading: "but", topic: "art", level: "TOPIK2", notes: "" },
    { korean: "캔버스", english: "canvas", reading: "kaenbeoseu", topic: "art", level: "TOPIK2", notes: "" },
    { korean: "화학", english: "chemistry", reading: "hwahak", topic: "chemistry", level: "TOPIK3", notes: "" },
    { korean: "생물", english: "biology", reading: "saengmul", topic: "chemistry", level: "TOPIK3", notes: "" },
    { korean: "실험", english: "experiment", reading: "sirheom", topic: "chemistry", level: "TOPIK3", notes: "" },
    { korean: "원소", english: "element", reading: "wonso", topic: "chemistry", level: "TOPIK4", notes: "" },
    { korean: "분자", english: "molecule", reading: "bunja", topic: "chemistry", level: "TOPIK4", notes: "" },
    { korean: "반응", english: "reaction", reading: "baneung", topic: "chemistry", level: "TOPIK3", notes: "" },
    { korean: "영어", english: "English", reading: "yeongeo", topic: "chemistry", level: "TOPIK1", notes: "" },

    // === EVERYDAY PHRASES ===
    { korean: "안녕하세요", english: "Hello (formal)", reading: "annyeonghaseyo", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "감사합니다", english: "Thank you", reading: "gamsahamnida", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "죄송합니다", english: "I'm sorry", reading: "joesonghamnida", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "괜찮아요", english: "It's okay / I'm fine", reading: "gwaenchanayo", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "잘했어", english: "You did well / Good job", reading: "jalhaesseo", topic: "phrases", level: "TOPIK1", notes: "Informal encouragement" },
    { korean: "화이팅", english: "Fighting! / You can do it!", reading: "hwaiting", topic: "phrases", level: "TOPIK1", notes: "Konglish but essential" },
    { korean: "사랑해", english: "I love you (informal)", reading: "saranghae", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "보고 싶어", english: "I miss you", reading: "bogo sipeo", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "오늘", english: "today", reading: "oneul", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "내일", english: "tomorrow", reading: "naeil", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "어제", english: "yesterday", reading: "eoje", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "지금", english: "now", reading: "jigeum", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "나중에", english: "later", reading: "najunge", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "어디", english: "where", reading: "eodi", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "언제", english: "when", reading: "eonje", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "뭐", english: "what", reading: "mwo", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "왜", english: "why", reading: "wae", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "어떻게", english: "how", reading: "eotteoke", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "많이", english: "a lot / very", reading: "mani", topic: "phrases", level: "TOPIK1", notes: "" },
    { korean: "조금", english: "a little", reading: "jogeum", topic: "phrases", level: "TOPIK1", notes: "" },
];

// Topic metadata for UI
const TOPIC_METADATA = {
    home: { icon: "🏠", label: "Home Life", color: "#E74C3C" },
    cat: { icon: "🐱", label: "Cat", color: "#F39C12" },
    garden: { icon: "🌱", label: "Garden", color: "#27AE60" },
    church: { icon: "⛪", label: "Church & Faith", color: "#9B59B6" },
    music: { icon: "🎵", label: "Music", color: "#E91E63" },
    family: { icon: "👨‍👩‍👧‍👦", label: "Family", color: "#FF5722" },
    rent: { icon: "🏠", label: "Rent & House", color: "#795548" },
    medical: { icon: "🏥", label: "Medical", color: "#2196F3" },
    art: { icon: "🎨", label: "Art", color: "#FF9800" },
    chemistry: { icon: "⚗️", label: "Chemistry & Biology", color: "#00BCD4" },
    phrases: { icon: "💬", label: "Everyday Phrases", color: "#607D8B" },
};

// TOPIK level thresholds
const TOPIK_LEVELS = {
    TOPIK1: { name: "TOPIK I Level 1", minCards: 0, description: "Beginner - basic survival Korean" },
    TOPIK2: { name: "TOPIK I Level 2", minCards: 50, description: "Elementary - simple conversations" },
    TOPIK3: { name: "TOPIK II Level 3", minCards: 150, description: "Intermediate - daily life fluency" },
    TOPIK4: { name: "TOPIK II Level 4", minCards: 300, description: "Upper-Intermediate - social fluency" },
    TOPIK5: { name: "TOPIK II Level 5", minCards: 500, description: "Advanced - professional contexts" },
    TOPIK6: { name: "TOPIK II Level 6", minCards: 800, description: "Proficient - near-native fluency" },
};

// Reading practice sentences (progressive difficulty)
const READING_SENTENCES = [
    { korean: "안녕하세요. 저는 의사예요.", english: "Hello. I am a doctor.", level: 1 },
    { korean: "고양이가 귀여워요.", english: "The cat is cute.", level: 1 },
    { korean: "오늘 날씨가 좋아요.", english: "The weather is good today.", level: 1 },
    { korean: "밥 먹었어요?", english: "Did you eat?", level: 1 },
    { korean: "교회에 가요.", english: "I go to church.", level: 1 },
    { korean: "우리 집에 고양이가 한 마리 있어요.", english: "We have one cat at our house.", level: 2 },
    { korean: "매일 밤 한국어를 공부해요.", english: "I study Korean every night.", level: 2 },
    { korean: "아내는 예술을 좋아해요.", english: "My wife likes art.", level: 2 },
    { korean: "정원에서 꽃을 심었어요.", english: "I planted flowers in the garden.", level: 2 },
    { korean: "주일마다 교회에 가서 예배를 드려요.", english: "Every Sunday I go to church and worship.", level: 2 },
    { korean: "5년 후에 한국에서 의사 시험을 볼 거예요.", english: "In 5 years, I will take the doctor exam in Korea.", level: 3 },
    { korean: "가정의학과 의사로서 환자들을 돌보고 싶어요.", english: "As a family medicine doctor, I want to care for patients.", level: 3 },
    { korean: "아내와 함께 노래하고 음악을 연주하는 것을 좋아해요.", english: "I like singing and playing music with my wife.", level: 3 },
    { korean: "은혜로운 하나님의 사랑을 매일 느껴요.", english: "I feel God's gracious love every day.", level: 3 },
    { korean: "한국에 가면 장인어른과 장모님을 뵙고 싶어요.", english: "When I go to Korea, I want to meet my parents-in-law.", level: 3 },
];
